# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c8b9b2f75e52a3fe0477757e59f1b6aa639039de24759c55e94155f3c320971b76c8d5f3281e1f202f21cc33ac4a8a1aba99a5035c2dd92ea4d7808ce7e7618

test:
  secret_key_base: 1bd8fa4833f36f739a69389ad39d24e751eb13d3ed3b77764bcf18d668d950ecf1f12a6b4d3390c05aa7d5df9241691a47a1866b220dd79ae53b89a8fb60c73f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
